version: '3.8'

services:
  qwenproxy:
    build: .
    env_file:
      - .env
    volumes:
      - ./qwen_profile:/app/qwen_profile
    restart: always
    expose:
      - "8080"
    networks:
      - coolify

networks:
  coolify:
    external: true